### ISSUE TITLE
Install from HACS

### ISSUE THREAD

**Issue by alesnav** [algirdasc/hass-components#10] opened 2020-01-29 13:25 UTC
Hello!
I tried to install Fluoreon component from HACS without success.
Is it possible? How can I do it?
This way, it will be always updated. If done manually, updates are manually applied too...
Thanks!

**Comment by rege245** [comment] 2020-02-16 17:57
stopped working few days ago ;(

**Comment by algirdasc** [comment] 2020-04-09 08:47
Duplicate of #13

**Closed as completed by algirdasc** 2020-04-09 08:47 UTC

**Comment by alesnav** [comment] 2020-04-22 22:29
Hello @algirdasc ,

You have closed both issues, this one and #13 , but I guess this cannot be installed from HACS yet. Can you please reopen one of them to be able to track the status?

Thanks!
